services:
  pgvector:
    image: ankane/pgvector
    container_name: pgvector
    restart: unless-stopped
    env_file:
      - .env.deployment
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    networks:
      - tyba-net

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - tyba-net

  tyba:
    build:
      context: .
    container_name: tyba
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.deployment
    depends_on:
      - pgvector
      - redis
    networks:
      - tyba-net

volumes:
  pgvector-data:

networks:
  tyba-net:
    driver: bridge
